### PR TITLE
Optional subtitle

### PR DESCRIPTION
**Pull request by stasinos**
Optionally, provide a subtitle, typeset in the header, in smaller font.

Not very happy with how it looks when the menu is reduced to burger, but cannot figure out where to control positioning when responsive'ing for a narrow screen. Please help.

### CODE REVIEW

**Comment by sylhare** [comment]
What do you mean by subtitles? 

You mean text under the description in the main banner as the date in a post?

**Comment by stasinos** [comment]
Please see here http://deg.iit.demokritos.gr, a site using a modified Type-on-Strap, where I am using an earlier version of this PR that doesn't correct the margin. It has a smaller subtitle under the "Robotics activity" title. The current PR improves the placement relative to the avatar, but only when the menu is shown, not when the burger is shown.

**Comment by sylhare** [comment]
Ok I will take a look at it later then ;)

**Comment by sylhare** [comment]
After looking at it, I prefer not to add this one on the theme.
Thanks for the pull request.

**Pull request closed without merging**
