### PR TITLE
Replaced baseurl with relative_url, improved pagination

### PR DESCRIPTION
**Pull request by CookiePLMonster**
This PR contains two separate changes, mostly cause I couldn't make one depend on the other.

1. The first commit changes all instances of `site.baseurl` to `relative_url`. This improves readability and handles all the cases of `//` implicitly - so the workaround present in pagination could be removed.
2. The second commit improves paginator to contain First/Last buttons, if needed. I wanted to use `fa-chevron-double` for the icon but it is only available in Pro.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
There are a few issues with 2. which I'm not sure how to address:

- Page number isn't centered, so it ends up being placed to the left on first page and to the right on the last page.
- Buttons wrap to the second line when viewed on mobile.

I am not sure how to resolve those issues myself, do you have any ideas?

**Comment by sylhare** [comment]
Hey!

Thanks for the PR.
I like the replacement with the relative url! Nice touch :smile:

For the last and first in pagination, you wanted something like:
`[<<] [prev] 1 [next] [>>]`?

I will try this one on my side and look at the issue you mentioned. That'd be a good idea to have a way to go to first/last page in case you have a lot of articles.

**Comment by CookiePLMonster** [comment]
Yep! That's what I added in my PR and it works fine. The problem is positioning - I'd like the
X / Y
to be always centered and buttons going to the sides, which isn't the case atm.

**Comment by CookiePLMonster** [comment]
That would work too, yes.
Also, that's how it looks on mobile at the moment - this is what I meant by navigation controls going into another line:
image

**Comment by sylhare** [comment]
I will merge this one for now, we can update the pagination buttons later. I will open an enhancement issue for this one 😉

**Pull request merged**
