### PR TITLE
 Add author's avatar option

### PR DESCRIPTION
**Pull request by mhagnumdw**
# **==> Please review what I modified !!! <==**

Solves #154 

If responsiveness and css are 100% correct, I don't know! :grimacing:

Let me know if you want to change anything.

off-topic: If the PR is accepted, how about doing a squash for the master to avoid getting the tree dirty?

Preview
[Add-author-s-avatar-option](https://www.kapwing.com/videos/5cef31e7c8d5320013b4d5d5)

### CODE REVIEW

**Comment by sylhare** [comment]
Thanks, I will review that 😉

**Comment by sylhare** [comment]
Hi, I was testing on my side and for some reason the avatar appears blank. Did you have this kind of trouble?

**Comment by mhagnumdw** [comment]
Hi!

With avatars... all right here. Tested on: Chrome 73, FF 61 and 63, Vivaldi, Opera and Brave

But I noticed that FireFox is not displaying webp. I rarely use FireFox. Eg: header_feature_image

**Comment by sylhare** [comment]
Oh I will try again then ;)

**Comment by mhagnumdw** [comment]
> But I noticed that FireFox is not displaying webp. I rarely use FireFox. Eg: header_feature_image

:grimacing: ohh, @sylhare I just updated my branch with the master now... and now that you converted webp into jpg, the problem in FireFox is gone

**Comment by sylhare** [comment]
Yup all working now. I like it 😄 
I might do some changes to get some more articles with author and some without to see how it goes 😉

**Pull request merged**
