### PR TITLE
Option to hide the title in posts

### PR DESCRIPTION
**Pull request by stasinos**
Adds the option to not show the title of a post. This is useful for me for posts in a portfolio of projects, where the feature image is the logo of the project, and the name of the project is shown prominently in the logo so it would look silly to also overlay it, as per the default behaviour. I tried simply setting the title to the empty string, but it breaks other places , such as the Tags page.

### CODE REVIEW

**Comment by sylhare** [comment]
Hi
Thanks for the PR

So you want the ability not to display the title for posts (it can be from the portfolio or from a blog post). Well I think that's a valid point.

I was thinking of:
- [ ] Have `hide_title` instead of `hidetitle` because usually `_` is used to seperate the words. 
- [ ] Have this keyword documentation added in the `post` section of the readme.

**Comment by stasinos** [comment]
Hi,
OK on both counts, please check.
You can see why I need it here:
https://data-eng.github.io/projects (under construction, but it gives you the idea)

**Comment by sylhare** [comment]
Perfect! Thanks :wink:

**Comment by stasinos** [comment]
True works too.

**Comment by sylhare** [comment]
Good point, let's keep it boolean :wink:

**Pull request merged**
