### PR TITLE
Improved readability of text above featured images

### PR DESCRIPTION
**Pull request by lbcnz**
I changed the shadow size to be relative to the font size and applie it also to the subtitle (post-info class). Also did a number of small related changes.

### CODE REVIEW

**Comment by sylhare** [comment]
Thanks! You are giving me a lot of things to review ahah 😄

**Review by sylhare — COMMENTED** [review]
It looks nice on the feature image post.
The only downside is when there's no feature image, the shadow seems a bit too strong:

before
image

Now
image

I suppose the new shadow could be under `.feature-img h1.title` and the `h1.title` could keep the previous shadow. Something like that 🤔

**Comment by lbcnz** [comment]
Done.

I also did a selector simplification that I'm not 100% sure is ok.

**Comment by sylhare** [comment]
Thanks, yeah the scss was a good idea but a bit dodgy, it was rendering extra stuff with shadow, so I updated it and now it's all good 😉

**Pull request merged**
