### PR TITLE
Add date localization formating in config.yml

### PR DESCRIPTION
**Pull request by Nikurasukun**
My goal was to localize the date format so that on non-english websites all written Months and Days are replaced with the correct terms for the country. I wasn't yet able to get this working, but I will share, what I've achieved so far. But I will keep working on it.

### CODE REVIEW

**Comment by sylhare** [comment]
Alright let me know how it goes, I would like to see in a screenshot how different it appears from one format to another

**Comment by sylhare** [comment]
I can convert this pull request to "draft" until it's ready if you want @Nikurasukun 
So that it stays there and you can continue working on it 👍

**Comment by Nikurasukun** [comment]
Ok, I tried it in my holdays, but I don't get it working, sorry the formating is the most I can achieve.

**Comment by sylhare** [comment]
Alright, I will take a look

**Comment by lbcnz** [comment]
I made a PR with localization for months. The same logic can be applied to the days of the week.

**Comment by sylhare** [comment]
I believe the localization was mainly for the month. In term of date formatting, that's another subject.
So I will close this PR as I consider it implemented.

**Pull request closed without merging**
