### PR TITLE
Utterances bug fix

### LINKED ISSUE #302: Comments from utterances doesn't seem to show up.
image

I added the required config in _config.yaml. Comment box doesn't show up in blog posts. What am I doing wrong? Utterances is installed and access is grated to all repos.

### PR DESCRIPTION
**Pull request by coder-lg**
fixes #302 and #303
303 is mine btw

### CODE REVIEW

**Comment by sylhare** [comment]
No need, but thanks for your reactivity :)

**Comment by coder-lg** [comment]
okay but that change is recommended. If the user needs to enable the theme, it might be a stir. And also, specify that no double quotes be used in the config in the readme.

**Comment by sylhare** [comment]
You can use double quotes I just tried it.

**Comment by coder-lg** [comment]
check #302 there the user tried double quotes but comments showed up on every site.

**Comment by coder-lg** [comment]
color_theme ain't working, like I set in auto for reader's choice but Utterances doesn't accept it.

**Pull request closed without merging**
