### PR TITLE
Action 2: Issue and project triage workflow

### PR DESCRIPTION
**Pull request by im-coder-lg**
### What this does
Says a `thank you` for opening an issue and adds it to triage if the issue has `bug` label.

### CODE REVIEW

**Comment by coder-lg** [comment]
@sylhare ready to merge

**Comment by coder-lg** [comment]
I updated the PR branch too.

**Comment by coder-lg** [comment]
@sylhare

**Comment by coder-lg** [comment]
I will add this workflow's info to the `./.github/Docs.md`

**Comment by coder-lg** [comment]
@sylhare

**Comment by coder-lg** [comment]
Ping @sylhare

**Comment by sylhare** [comment]
I have looked into that triage action, I am not sure I need it.

**Comment by coder-lg** [comment]
wdym? it just automatically adds a bug report to triage. if you merge #308, this will be perfect. Users will have a bug report template that automatically adds the bug label which adds the bug to triage. But, as of late, it has been failing on my repo, and I can't find a fix.

**Comment by coder-lg** [comment]
Maybe, I will remove the triage part but keep the issue comment part. Merge #308 before this.

**Comment by coder-lg** [comment]
yup done that

**Comment by coder-lg** [comment]
comment part works

**Comment by coder-lg** [comment]
try this :)

**Comment by coder-lg** [comment]
Figured out the automation for triage @sylhare you really don't need it?

**Comment by sylhare** [comment]
I think I am ready to try it out 👍

**Pull request merged**
