### PR TITLE
Probot app configurations

### PR DESCRIPTION
**Pull request by coder-lg**
@sylhare I did as you told on #298 but I can add the other PR only when you merge *__this__* one.

### CODE REVIEW

**Comment by coder-lg** [comment]
There might be conflicts while merging

**Comment by coder-lg** [comment]
But I have an idea. Why not I make another PR with the app configs to this branch, and you can review in that PR for the apps. How about that?

**Comment by coder-lg** [comment]
I will try that

**Comment by coder-lg** [comment]
the app configs pr is [`here`](https://github.com/coder-lg/Type-on-Strap/pull/1)

**Comment by coder-lg** [comment]
or any other method?

**Comment by sylhare** [comment]
Merge conflict is not an issue we can always fix them.
And if you build on top of each PR that shouldn't be an issue.
As long as you can create small ones. 

I would rather do the ones for the config of the bots first, then we'll do the others 👍

**Comment by coder-lg** [comment]
Ok.

**Comment by coder-lg** [comment]
PR is [__*here*__](https://github.com/coder-lg/Type-on-Strap/pull/2)

**Comment by coder-lg** [comment]
for workflows

**Comment by coder-lg** [comment]
I will merge workflows into this and you can merge everything in one click.

**Comment by coder-lg** [comment]
got an idea [`here`](https://github.com/coder-lg/Type-on-Strap/pull/2). Do you have an official GitHub account which people can reply to? I was investigating issue templates and it showed me how to add a `config.yml` inside the issue templates folder in **THAT** PR, not this, and it allowed adding `contact me` links. So, a lil' bit curious, don't use your real email, get the one GitHub allows for each user and post it here. I will use that for the config. It even allows to block out blank issues(issues without templates)

**Comment by coder-lg** [comment]
@sylhare what about the workflows I added in the other branch?

**Pull request merged**
