### PR TITLE
Updated Mermaid and Simple-jekyll-search to latest version

### PR DESCRIPTION
**Pull request by lbcnz**
They are working on my initial gulp branch and should be working here too.

### CODE REVIEW

**Comment by sylhare** [comment]
Seems like the search function does not work anymore with this update:
```
ReferenceError: SimpleJekyllSearch is not defined
```
Maybe the API has changed.

And I get a strange warning with mermaid (which was not present before):
```
Source map error: Error: request failed with status 404
Resource URL: http://127.0.0.1:4000/Type-on-Strap/assets/js/vendor/mermaid.min.js
Source Map URL: mermaid.min.js.map
```

**Comment by lbcnz** [comment]
I will look at it. That strange error is the map file that I deleted but left somehow a reference to it. The search is working in the first branch so I must have missed something.

**Comment by lbcnz** [comment]
Fixed both.

**Review by sylhare — COMMENTED** [review]
I don't think we need to keep the `.map` for mermaid as we don't need to debug it. 
I tried using the v8.9.1 directly from the [release source](https://github.com/mermaid-js/mermaid/releases/tag/8.9.1) and the warning is not showing up anymore.

**Comment by lbcnz** [comment]
Yep. Just added this:
`/* @license Mermaid 8.9.1 MIT License */`

And I get the error after removing the `.map`.

**Comment by lbcnz** [comment]
Which is solved by removing the reference to it on `mermaid.min.js`.

**Review by sylhare — APPROVED** [review]

**Pull request merged**
