### PR TITLE
Image preview: in WhatsApp, feed readers and others

### PR DESCRIPTION
**Pull request by mhagnumdw**
_(draft)_

Hi!

Let me know if you are interested in continuing this task. I think it's worth it, but we'll have to see the issue since the default images in the project is **webp**.

I needed to generate:
triangle **.svg** > triangle **.png**
desk-messy **.webp** > desk-messy **.jpg**

### WhatsApp
type on strap print thumbnail blog no whatsapp

### https://feedly.com
Antes Peek 2019-05-30 13-20

### WhatsApp
Depois whatsapp

### https://feedly.com
Depois Peek 2019-05-30 13-10

### CODE REVIEW

**Comment by sylhare** [comment]
This is good feedback!

I have added this new `.webp` format because it is recommended as new and lightweight for the internet.  It's too bad that `webp` is not yet recognized by those apps and feed readers. 

I believe that on a normal use people would use `jpg` and `png`. (Even though I have added the gulp task for `.webp` if one wants to reduce the image load on the website).

I know there's a new `jpg` format that is highly compressed, if it works with it, we could switch to this one for the sake of having the image displayed. I would need to investigate on that.

The goal would be to find a lightweight format that can also be displayed on those feeds.

**Comment by sylhare** [comment]
The other jpg format (`JPEG XR` and `JPEG 2000`) are even less supported that `webp`. Maybe we can add jpg images for the ones on the blog. or add a warning for `webp` format?

**Comment by mhagnumdw** [comment]
For a same image we could have two versions: `jpg` and `webp`?
`jpg` if necessary, of course.

**Comment by sylhare** [comment]
I will for the theme put the images that are seen in jpeg. I will merge you change with the feed.xml and the `.png` image.
I have tried a bit for having both (like a fallback) and it's complicated without js 😅

**Comment by sylhare** [comment]
Nice! Thanks ;)

**Pull request merged**
