### PR TITLE
Update gem dependencies

### PR DESCRIPTION
**Pull request by sylhare**
Use latest Jekyll-feed: https://github.com/jekyll/jekyll-feed
Use latest Jekyll-Seo-tag: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

I need it to be compatible with GitHub page https://github.com/github/pages-gem

```
+------------------------------+---------+
| Gem                          | Version |
+------------------------------+---------+
| jekyll                       | 3.9.0   |
| jekyll-sass-converter        | 1.5.2   |
| kramdown                     | 2.3.1   |
| kramdown-parser-gfm          | 1.1.0   |
| jekyll-commonmark-ghpages    | 0.1.6   |
| liquid                       | 4.0.3   |
| rouge                        | 3.26.0  |
| github-pages-health-check    | 1.17.9  |
| jekyll-redirect-from         | 0.16.0  |
| jekyll-sitemap               | 1.4.0   |
| jekyll-feed                  | 0.15.1  |
| jekyll-gist                  | 1.5.0   |
| jekyll-paginate              | 1.1.0   |
| jekyll-coffeescript          | 1.1.1   |
| jekyll-seo-tag               | 2.7.1   |
| jekyll-github-metadata       | 2.13.0  |
| jekyll-avatar                | 0.7.0   |
| jekyll-remote-theme          | 0.4.3   |
| jekyll-include-cache         | 0.2.1   |
| jemoji                       | 0.12.0  |
| jekyll-mentions              | 1.6.0   |
| jekyll-relative-links        | 0.6.1   |
| jekyll-optional-front-matter | 0.3.2   |
| jekyll-readme-index          | 0.3.0   |
| jekyll-default-layout        | 0.1.4   |
| jekyll-titles-from-headings  | 0.5.3   |
| minima                       | 2.5.1   |
| jekyll-swiss                 | 1.0.0   |
| jekyll-theme-primer          | 0.6.0   |
| jekyll-theme-architect       | 0.2.0   |
| jekyll-theme-cayman          | 0.2.0   |
| jekyll-theme-dinky           | 0.2.0   |
| jekyll-theme-hacker          | 0.2.0   |
| jekyll-theme-leap-day        | 0.2.0   |
| jekyll-theme-merlot          | 0.2.0   |
| jekyll-theme-midnight        | 0.2.0   |
| jekyll-theme-minimal         | 0.2.0   |
| jekyll-theme-modernist       | 0.2.0   |
| jekyll-theme-slate           | 0.2.0   |
| jekyll-theme-tactile         | 0.2.0   |
| jekyll-theme-time-machine    | 0.2.0   |
+------------------------------+---------+

```

<a href="https://gitpod.io/#https://github.com/sylhare/Type-on-Strap/pull/337"></a>

### CODE REVIEW

**Comment by im-coder-lg** [comment]
@sylhare have you thought of any new features for Type on Strap?

**Comment by sylhare** [comment]
Yeah I have been adding / updating stuff. If there's a particular feature you are interested in having here let me know

**Comment by im-coder-lg** [comment]
Netlify CMS support?

**Comment by sylhare** [comment]
You can open an issue with it, but I doubt there's anything to do on the theme side, it's more of Netlifty being compatible with Jekyll.

**Pull request merged**
