### PR TITLE
Flip previous and next

### PR DESCRIPTION
**Pull request by jss367**
It looks like the previous and next posts got flipped around.

### CODE REVIEW

**Comment by sylhare** [comment]
Yeah it's intended it matches the blog navigation and within the posts navigation.
I like having `next` to the right.

**Comment by jss367** [comment]
@sylhare I just want to make sure I understand because I also like having `next` to the right and I may have just messed up the code. In the case of `[sample-post](https://sylhare.github.io/Type-on-Strap/2019/06/30/sample-post.html)`, the Previous Post is listed as `Dark Mode` and the Next Post is listed as `Color Post`. However, `Dark Mode` is the most recent post. So if you click Previous Post until you can't anymore you end up with the latest, and if you click Next Post until you can't anymore you with up with the oldest. Is this the desired behavior?

**Comment by sylhare** [comment]
Yep all intended behaviour,

Since the blog navigation is latest page first next to the right, I wanted the same thing inside the posts as well.

So next means next in the list of posts starting from the first one in the first page to the last one in the last page.

I did not consider the post date in how I put next or previous. Time is relative 😛

**Comment by jss367** [comment]
OK, I just wanted to make sure. I'll probably switch it on my end then. Thanks for the beautiful theme!

**Pull request closed without merging**
