### PR TITLE
Assets and gulpfile improvements

### PR DESCRIPTION
**Pull request by lbcnz**
This is a work in progress. Thus far I:

- Added `/vendor/` (local gems) to `.gitignore` #249  
- Moved non-assets like gulp helper and Dockerfile to `lib/`.
- Splitted `js` into `js` for distribution files and `_js` for source scripts to be concatenated and uglified.
- Splitted `img` into `img` and `_img` for source images to be optimized.
- Updated vendor scripts, simple-jekyll-search and mermaid, to latest version. 
- Rewrote `gulpfile.js` entirely providing a non-destructive incremental optimization flow. #250
- Wrote a git pre-commit hook.
- Updated README.md.

### CODE REVIEW

**Comment by sylhare** [comment]
That's pretty packed with new stuff.
I have to say that some of the file were intentionally placed into assets as I didn't want for somebody that wouldn't use them to be scared away by the amount of files visible in root.

**Comment by lbcnz** [comment]
> I have to say that some of the file were intentionally placed into assets as I didn't want for somebody that wouldn't use them to be scared away by the amount of files visible in root.

I can put them in a lib dir.

**Comment by lbcnz** [comment]
Double checked everything.

**Comment by sylhare** [comment]
I will have to take some time to review it all calmly, thanks for your PR. 👍

**Comment by sylhare** [comment]
Do you think you can break down this pull request into multiple smaller ones? That would be easier to keep track and I'll be able to process them much faster.

**Comment by lbcnz** [comment]
I will try it later.

**Comment by lbcnz** [comment]
Finished breaking it in smaller PRs so I am closing this.

**Pull request closed without merging**
