### PR TITLE
Fix link color for headers

### PR DESCRIPTION
**Pull request by danisztls**
Do not break link color for other elements as #271 did.

### CODE REVIEW

**Comment by sylhare** [comment]
The issue I see is in the `tag` page where I'd like to keep them black:

image

Instead of all blue with this new PR:

image

Do you have an example of where it would not render, maybe in blog post?

**Comment by sylhare** [comment]
Oh I see, here:

image

**Comment by danisztls** [comment]
> It feels like a feature, you put link when you don't want colors and no links when you want colors

Maybe.

I can fix the tags page.

**Comment by sylhare** [comment]
Well seems like it's all good as of now, so I'll close this one :)

**Pull request closed without merging**
