### PR TITLE
Added optional multilingual support

### PR DESCRIPTION
**Pull request by musicmichaelc**
# Optional multilingual support

Can be used in conjunction with the multilingual [polyglot plugin](https://github.com/untra/polyglot).  
For those who don't need multilingual support / support for localizing other languages, ***the previous settings/default behavior will continue to apply***.

## Features / usage:

- Multilingual features can be enabled by including `multilingual: true` in `_config.yml`  
If not set, the previous default behavior continues to apply
- If one doesn't have a multilingual site but wants to use a language other than English, one can set the language in `_config.yml` using `language: `, e.g. `language: de`  
That way, the `<html lang=...>` tag at the top of each page will reflect the language one is using.  
- Date formats can be localized/customized in `language.yml`, e.g. `date_format: "%d. %B, %Y"`.  
If one is using the polyglot plugin, one can place a `language.yml` file each into a separate directory for each language in `_data`, e.g. `_data/en/language.yml`, `_data/de/language.yml`---polyglot will automatically fetch the date_format (as well as all the other strings) according to the currently selected language.  
Otherwise, one can of course customize the date format (for a one-language site) in `_data/language.yml`   
- Capability to customize the  word order of localized strings strings with `"%s"`:  in languages other than English, this will sometimes be necessary, i.e. in German, "Auf Facebook folgen" is grammatically better than "Folgen auf Facebook"
This can now easily be implemented  by adding for example, ` str_follow_on: "Auf %s folgen"`  to the `language.yml` data file. The same can be done with `str_add_to`.
If no `"%s"` is specified in the localization string, the default behaviour of
appending it to the end will be applied.  
Also added `str_share` to `language.yml`---so that this can also be localized/translated if needed.  
- Language switcher in navbar: the language names need to be configured in _data/lang-names in order in implement this, e.g.:
```yaml
en: "English"
de: "Deutsch"
```
- Site title, description, header_text and footer_text are rendered according to the currently selected language (if `multilingual: true` is set). In order for this to work, one must create an entry for each language for each of the four site variables, e.g.:
```yaml
title:
  en: Site title
  de: Titel der Website
description:
  en: About this website
  de: Über diese Webseite
...


```

Suggestions for improvement and  / or corrections are of course very welcome.

### CODE REVIEW

**Comment by sylhare** [comment]
I am not familiar with the polyglot plugin, do you need it for the multilingual to work?

**Comment by musicmichaelc** [comment]
One would need the plugin for all of the things to work&mdash;at least the way it is written at the moment&mdash;because the code references  
1. `site.active_lang`&mdash;which is a **site variable provided by the plugin** that makes it convenient to obtain the currently selected language  
2. `site.data.language` which the plugin will *automatically expand* to `site.data.active_lang.language`, i.e. it will fetch data from `_data/fr/language.yml` if one has selected french, or  `_data/de/language.yml` if German is selected, etc.


However, although these things are certainly more convenient with the plugin, I think it would be feasible to find a work-around if one wanted to be able to do it without the plugin. For example, one could  get the current language by going through the list of languages (`site.languages`) and checking the page.url if it contains one of those language tags at the beginning&mdash;if not, then the current language would be the so-called `site.default_lang`...  

&mdash;presupposing one put the "default language" at the root directory of the site, and the other languages (such as `de, fr, zh...` each into directories above the root level, e.g. `/de/`, `/fr/` etc. _(which is the way the plugin organizes the site/helps one organize it)_.

**Comment by danisztls** [comment]
The problem of using plugins is losing GH Pages support. Recently I did something similar without plugins but it is tricky and I used a JS (not needed) for browser locale detection and auto-redirection.
https://github.com/EpicBounties/epicbounties.github.io/tree/new-site

**Comment by sylhare** [comment]
Indeed, only a selected number of plugin are validated by GitHub.

**Comment by sylhare** [comment]
As it requires another gem not compatible with github page, I won't merge this one

**Pull request closed without merging**
