### PR TITLE
suggested formatting for code

### PR DESCRIPTION
**Pull request by Jeansen**
Here is what it looks like in action:

selection_010

---
This change is [Reviewable](https://reviewable.io/reviews/sylhare/type-on-strap/42)

### CODE REVIEW

**Comment by Sylhare** [comment]
Thanks for the PR, I'll review it ;)

**Comment by Sylhare** [comment]
There is another PR (#45) regarding code format (generated from the markdown). I will see what comes out better. They might be related.

**Comment by Sylhare** [comment]
Made me realize that I could update the formatting, I have come up with #47 which is more in my taste.
Thanks for your suggestion 👍

**Comment by Jeansen** [comment]
oh..cool. I like #47, too :)

**Pull request closed without merging**
